In [ ]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [ ]:
import numpy as np
arr=np.zeros((8,8))
print(arr)
arr[:1]=1

arr[0]=1
arr[0:,7]=1
arr[1:,0]=1
arr[7]=1

print("\n",arr)

In [ ]:
"""
to create a dataframe from a dictionary and display it
"""
import pandas as pd

arr=pd.DataFrame({'Name':['Malay','Deva','Hitesh','Tanvi'],'Semester':[5,5,4,6]})
print(arr)

In [ ]:
"""
to sort the DataFrame first by 'name' in ascending order
"""

import pandas as pd

arr=pd.DataFrame({'Name':['Malay','Deva','Hitesh','Tanvi','Daksh'],'Semester':[5,5,4,6,5]})
print("Before sorting")
print("\n",arr)
sort_arr=arr.sort_values(by=['Name'],ascending=True)
print("\n After sorting")
print(sort_arr)

In [ ]:
"""
to delete the one specific column from the DataFrame

"""

import pandas as pd

arr=pd.DataFrame({'Name':['Malay','Deva','Hitesh','Tanvi','Daksh'],'Semester':[5,5,4,6,5],'Enrollment':[85,63,83,100,76]})
print(arr)
del arr['Semester']

print("\nAfter deleting semester")
print("\n",arr)

In [ ]:
"""
 to write a DataFrame to CSV file using tab separator
"""
import pandas as pd

arr=pd.DataFrame({'Name':['Malay','Deva','Hitesh','Tanvi','Daksh'],'Semester':[5,5,4,6,5],'Enrollment':[85,63,83,100,76]})
print(arr)

arr.to_csv("/kaggle/working/semester.csv", sep=",",index=False)