# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
import pandas as pd


dataset = pd.read_csv('/kaggle/input/nifty50-stock-market-data/ADANIPORTS.csv')
print("Original Dataset :\n",dataset.loc[:,dataset.notna().all()],sep="",end="\n\n\n")
print("Dataset with row having NaN :\n",dataset.loc[:,dataset.isna().any()],sep="",end="\n\n\n")
print("Dataset with droped NaN :\n",dataset.dropna(how="any"),sep="",end="\n\n\n")

Original Dataset :
            Date      Symbol Series  Prev Close    Open     High     Low  \
0     2007-11-27  MUNDRAPORT     EQ      440.00  770.00  1050.00  770.00
1     2007-11-28  MUNDRAPORT     EQ      962.90  984.00   990.00  874.00
2     2007-11-29  MUNDRAPORT     EQ      893.90  909.00   914.75  841.00
3     2007-11-30  MUNDRAPORT     EQ      884.20  890.00   958.00  890.00
4     2007-12-03  MUNDRAPORT     EQ      921.55  939.75   995.00  922.00
...          ...         ...    ...         ...     ...      ...     ...
3317  2021-04-26  ADANIPORTS     EQ      725.35  733.00   739.65  728.90
3318  2021-04-27  ADANIPORTS     EQ      730.75  735.00   757.50  727.35
3319  2021-04-28  ADANIPORTS     EQ      749.15  755.00   760.00  741.10
3320  2021-04-29  ADANIPORTS     EQ      746.25  753.20   765.85  743.40
3321  2021-04-30  ADANIPORTS     EQ      746.75  739.00   759.45  724.50

       Last   Close    VWAP    Volume      Turnover  Deliverable Volume  \
0     959.0  962.90  984.72  27294366  2.687719e+15             9859619
1     885.0  893.90  941.38   4581338  4.312765e+14             1453278
2     887.0  884.20  888.09   5124121  4.550658e+14             1069678
3     929.0  921.55  929.17   4609762  4.283257e+14             1260913
4     980.0  969.30  965.65   2977470  2.875200e+14              816123
...     ...     ...     ...       ...           ...                 ...
3317  729.2  730.75  733.25   9390549  6.885658e+14              838079
3318  748.6  749.15  747.67  20573107  1.538191e+15             1779639
3319  743.4  746.25  751.02  11156977  8.379106e+14             1342353
3320  746.4  746.75  753.06  13851910  1.043139e+15             1304895
3321  726.4  730.05  743.35  12600934  9.366911e+14             3514692

      %Deliverble
0          0.3612
1          0.3172
2          0.2088
3          0.2735
4          0.2741
...           ...
3317       0.0892
3318       0.0865
3319       0.1203
3320       0.0942
3321       0.2789

[3322 rows x 14 columns]


Dataset with row having NaN :
        Trades
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
3317  116457.0
3318  236896.0
3319  130847.0
3320  153293.0
3321  132141.0

[3322 rows x 1 columns]


Dataset with droped NaN :
            Date      Symbol Series  Prev Close    Open    High     Low  \
866   2011-06-01  MUNDRAPORT     EQ      161.45  162.10  165.70  161.25
867   2011-06-02  MUNDRAPORT     EQ      164.00  164.00  165.15  160.15
868   2011-06-03  MUNDRAPORT     EQ      161.25  161.50  162.80  159.20
869   2011-06-06  MUNDRAPORT     EQ      161.05  160.50  161.10  159.05
870   2011-06-07  MUNDRAPORT     EQ      159.85  159.85  162.75  156.35
...          ...         ...    ...         ...     ...     ...     ...
3317  2021-04-26  ADANIPORTS     EQ      725.35  733.00  739.65  728.90
3318  2021-04-27  ADANIPORTS     EQ      730.75  735.00  757.50  727.35
3319  2021-04-28  ADANIPORTS     EQ      749.15  755.00  760.00  741.10
3320  2021-04-29  ADANIPORTS     EQ      746.25  753.20  765.85  743.40
3321  2021-04-30  ADANIPORTS     EQ      746.75  739.00  759.45  724.50

        Last   Close    VWAP    Volume      Turnover    Trades  \
866   163.50  164.00  164.08   2574106  4.223703e+13   19171.0
867   161.15  161.25  162.17   1699298  2.755678e+13   16176.0
868   161.00  161.05  161.02   1185817  1.909361e+13   14810.0
869   160.00  159.85  160.09    546378  8.746905e+12    7071.0
870   157.00  157.25  158.52   2193466  3.477027e+13   17865.0
...      ...     ...     ...       ...           ...       ...
3317  729.20  730.75  733.25   9390549  6.885658e+14  116457.0
3318  748.60  749.15  747.67  20573107  1.538191e+15  236896.0
3319  743.40  746.25  751.02  11156977  8.379106e+14  130847.0
3320  746.40  746.75  753.06  13851910  1.043139e+15  153293.0
3321  726.40  730.05  743.35  12600934  9.366911e+14  132141.0

      Deliverable Volume  %Deliverble
866              1271255       0.4939
867               791462       0.4658
868               722154       0.6090
869               386144       0.7067
870              1425849       0.6500
...                  ...          ...
3317              838079       0.0892
3318             1779639       0.0865
3319             1342353       0.1203
3320             1304895       0.0942
3321             3514692       0.2789

[2456 rows x 15 columns]